367441: Creating skeleton Processing API
DEFRA/stw-processing-api pull request #2
Opened 2024-05-02 07:38 UTC by sean-treanor

- Azure Function has HTTP Trigger that returns request payload and content type back in a response.
- Added unit tests
- Introduced Stylecop Analyzer

2024-05-02 10:05 UTC, reece-bennett requested changes

2024-05-02 10:05 UTC, reece-bennett commented on src/stylecop.ruleset
> +        <Rule Id="SA0002"  Action="Warning" />          <!-- Invalid settings file -->
Let's make these all errors

2024-05-02 12:04 UTC, reece-bennett approved these changes

2024-05-02 12:39 UTC, kamilmkainos approved these changes

2024-05-02 12:39 UTC, kamilmkainos commented on README.md
> +Following the competion of the steps above, the application should now be running on port `7071`.
typo in "competion", feel free to close

2024-05-03 08:54 UTC, subash-lakshmikanthan approved these changes

2024-05-13 07:45 UTC, merged