368678: Implementing validation rules
DEFRA/stw-processing-api pull request #6
Opened 2024-05-31 10:10 UTC by sean-treanor

- Adding initial rules
- Added unit test coverage

2024-05-31 14:24 UTC, reece-bennett requested changes

2024-05-31 14:24 UTC, reece-bennett commented on src/Stylecop/stylecop.ruleset
> +        <Rule Id="SA1010" Action="None"/>           <!-- Opening square brackets should be spaced correctly -->
Assume this was causing issues where it shouldn't have been on newer language features, if so try updating Stylecop to the latest preview version. The maintainer [has stated](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/3187#issuecomment-1043221630) that projects should use the beta versions as no stable release is planned

2024-05-31 14:24 UTC, reece-bennett commented on src/STW.ProcessingApi.Function/Constants/RuleErrorMessage.cs
> +    public const string SystemIdMissing = "Each trade line item must include \"applicableSpsClassification\" with a \"systemID\" of \"CN\"";
Does it make sense to put these and there error ids in the rule classes so it's closer to the implementation? Feels like it's something that should be owned by the rules?

2024-05-31 14:24 UTC, reece-bennett commented on src/STW.ProcessingApi.Function/Models/ErrorEvent.cs
> +public class ErrorEvent
Can we rename this `ValidationError`? Make more sense to me than error event

2024-05-31 14:24 UTC, reece-bennett commented on src/STW.ProcessingApi.Function/Models/ErrorEvent.cs
> +    public ErrorEvent(string errorMessage)
If we're having an error ID probably makes sense to make it required all of the time?

2024-06-03 08:10 UTC, sean-treanor commented on src/STW.ProcessingApi.Function/Models/ErrorEvent.cs
> +    public ErrorEvent(string errorMessage)
Not all of the rules in IPAFFS had error IDs so not sure where we plan to get them from?

2024-06-03 08:12 UTC, reece-bennett commented on src/STW.ProcessingApi.Function/Models/ErrorEvent.cs
> +    public ErrorEvent(string errorMessage)
Assign them the next highest free ID

2024-06-03 08:51 UTC, reece-bennett commented on src/STW.ProcessingApi.Function/Constants/RuleErrorMessage.cs
> +    public const string SystemIdMissing = "Each trade line item must include \"applicableSpsClassification\" with a \"systemID\" of \"CN\"";
Discussed offline, keeping here

2024-06-03 11:58 UTC, reece-bennett approved these changes

2024-06-03 12:37 UTC, kamilmkainos approved these changes

2024-06-04 14:52 UTC, reece-bennett commented on src/STW.ProcessingApi.Function/Services/ValidationService.cs
> +    public async Task InvokeRulesAsync(SpsCertificate spsCertificate)
Can we rename this to `InvokeRules`

2024-06-04 14:52 UTC, reece-bennett commented on src/STW.ProcessingApi.Function/Services/ValidationService.cs
> +            await rule.InvokeAsync(spsCertificate, validationErrors);
Can we rename this to `Invoke`

2024-06-04 15:01 UTC, reece-bennett commented on src/STW.ProcessingApi.Function/Rules/Interfaces/IAsyncRule.cs
> +    Task InvokeAsync(SpsCertificate certificate, IList<ValidationError> errors);
You called this one `certificate` and the one above `spsCertificate`. Go with `spsCertificate` for both.

2024-06-04 15:01 UTC, reece-bennett commented on src/STW.ProcessingApi.Function/Rules/Interfaces/IRule.cs
> +    void Invoke(SpsCertificate spsCertificate, IList<ValidationError> validationErrors);
Go with `errors` instead of `validationErrors` to match `IAsyncRule`

2024-06-05 08:41 UTC, sean-treanor commented on src/STW.ProcessingApi.Function/Services/ValidationService.cs
> +    public async Task InvokeRulesAsync(SpsCertificate spsCertificate)
Methods that have `async Task` should contain a suffix of `Async` to give visibility that they are async.

2024-06-05 08:41 UTC, sean-treanor commented on src/STW.ProcessingApi.Function/Services/ValidationService.cs
> +            await rule.InvokeAsync(spsCertificate, validationErrors);
Methods that have `async Task` should contain a suffix of `Async` to give visibility that they are async.

2024-06-05 11:06 UTC, merged