377004: Implement validation rule for Approved Establishment
DEFRA/stw-processing-api pull request #7
Opened 2024-06-03 15:44 UTC by sean-treanor

- Added Approved Establishment async rule
- Added unit tests

AB#377004

2024-06-05 12:11 UTC, reece-bennett commented on src/STW.ProcessingApi.Function/Rules/Common/TotalNetWeightRule.cs
> -    private const double MinWeight = 0.001;
Why were these bits removed?

2024-06-05 14:49 UTC, reece-bennett requested changes

2024-06-05 14:49 UTC, reece-bennett commented on src/STW.ProcessingApi.Function/Options/ApiConfigOptions.cs
> +    public string ApprovedEstablishmentBaseUrl { get; set; }
Add info on these to the readme

2024-06-05 15:09 UTC, sean-treanor commented on src/STW.ProcessingApi.Function/Rules/Common/TotalNetWeightRule.cs
> -    private const double MinWeight = 0.001;
We don't need them because the schema catches these. They are not testable outside of unit tests.

2024-06-06 08:41 UTC, reece-bennett approved these changes

2024-06-06 08:47 UTC, kamilmkainos approved these changes

2024-06-06 09:05 UTC, joshuahigginson approved these changes

2024-06-06 15:05 UTC, merged